# Build configuration
[build]
  # This tells Netlify to deploy the files from the root of your repository.
  publish = "."

# Redirects for clean URLs
[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200