# This is the main build configuration for your site
[build]
  # This command tells Netlify to first go into your functions folder
  # and run `npm install` before doing anything else.
  command = "npm install --prefix=netlify/functions"
  # This is the directory where your main site files are (index.html, etc.)
  publish = "."

# This configures your serverless functions
[functions]
  directory = "netlify/functions"
  # This specifies the modern and recommended way to bundle Node.js functions
  node_bundler = "esbuild"