# Build configuration
[build]
  command = "npm install --prefix=netlify/functions"
  publish = "."

# Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirect rule to make /api/* paths work
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200